### ISSUE TITLE
Allow configure fetch (mode, headers to add credentials, etc)

### ISSUE THREAD

**Issue by mastepanoski** [the-bugging/react-use-downloader#11]
**Is your feature request related to a problem? Please describe.**

I need to allow download links from another domain. I am getting this error: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource". It can be fixed by passing "mode: no-cors" to fetch.

If the link need any OAuth Token, or Cookie Token, it must allow passing the Authorization Header, and/or HTTP-Only Cookies.

**Describe the solution you'd like**

CORS: It can be fixed by passing  "mode: no-cors" to fetch. So you could add a "fetchProps" attribute (fetchProps={{ mode: 'no-cors' }}.
Authorization: It can be fixed by passing  "authorization: token" to fetch. So you could add a "fetchProps" attribute (fetchProps={{ credentials: 'include', authToken: token }}.

**Comment by olavoparno** [comment]
@mastepanoski first of all, thanks for the opened issue. I'll look into it as soon as I can.

**Comment by olavoparno** [comment]
@all-contributors please add @mastepanoski as idea and code

**Comment by olavoparno** [comment]
Hello again @mastepanoski could you please try again with version 1.2.1? Again, thanks for the issue!

**Comment by mastepanoski** [comment]
Hello @olavoparno, sorry for the delay.

Your proposal:

```
const { download } = useDownloader({
  mode: 'no-cors',
  credentials: 'include',
  headers: {
    Authorization: 'Bearer TOKEN',
  },
})
```
It is exactly what I expected.

I tested it in my project and now it works. I tried CORS and authorization using HTTP Only Cookies, but I've not tested it using JWT because the project I tried is not authorizing APIs using Authorization Headers.

Thanks a lot.

**Comment by olavoparno** [comment]
@mastepanoski glad it worked! Thank you again for the issue!
