### ISSUE TITLE
Headers are not working

### ISSUE THREAD

**Issue by nispot** [the-bugging/react-use-downloader#13]
Hi, is it possible that header are not passing to the request?
useDownloader({
    mode: 'no-cors',
    headers: {
      'access-control-allow-origin': 'http://localhost:3000',
      'access-control-allow-methods': 'PUT, GET, HEAD, POST, DELETE, OPTIONS',
    },
  });

because I cant see those, and also a I receive an opaque response :(

Thanks!

**Comment by olavoparno** [comment]
Hello, there. I may have written a bad options for fetch. Sorry. But the thing is, when you choose the mode 'no-cors', you only receive opaque responses. Ando also, I can see by your header `'access-control-allow-origin': 'http://localhost:3000/',` that you are trying to bypass cors but this is a header which you should set on the server, not on the client, so this is not going to work at all. 

https://stackoverflow.com/questions/39109789/what-limitations-apply-to-opaque-responses#:~:text=Opaque%20responses%20are%20defined%20as%20part%20of%20the,from%20JavaScript%20and%20as%20resources%20on%20a%20page%3F
