### ISSUE TITLE
Version 1.2.3 missing javascript?

### ISSUE THREAD

**Issue by bzbetty** [the-bugging/react-use-downloader#14]
installing version 1.2.3 seems to be missing the dist directory, if i fall back to 1.2.2 it works fine.

**Comment by olavoparno** [comment]
@bzbetty thanks for opening this issue. We'll look into it as soon as possible!

**Comment by olavoparno** [comment]
@all-contributors please add @bzbetty for bug

**Comment by olavoparno** [comment]
@bzbetty thank you again for your report. Please, care to test version 1.2.4?

**Comment by bzbetty** [comment]
Looks good to me.

**Comment by olavoparno** [comment]
Thank you again! Have a great week. Closing the issue.
