### ISSUE TITLE
Hey i'm experiencing some CORS issues, not sure why tho

### ISSUE THREAD

**Issue by AndonMitev** [the-bugging/react-use-downloader#16]
This is the source:

```
const { size, elapsed, percentage, download, cancel, error, isInProgress } =
    useDownloader({
     //  mode: 'no-cors'
    });

  const fileUrl = 'https://sample-videos.com/img/Sample-jpg-image-30mb.jpg';
  const filename = 'beautiful-carpathia.jpg';
```

with `mode: 'no-cors'` - I get opaque, like this 
<img width="264" alt="image" src="https://github.com/the-bugging/react-use-downloader/assets/32274987/4db863a4-a48a-4ab6-bf4e-b0dd3642aa2c">

any ideas?

**Comment by olavoparno** [comment]
Thanks for opening this issue, @AndonMitev but it seems the server you are trying to fetch this picture does not allow cross origin requests so there's nothing you can do from a client side perspective.

**Comment by ImranSefat** [comment]
Had the same issue as well for downloading a file from an S3 bucket. Then realized I did not configure the CORS policy for the bucket.
