### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by peranosborn** [the-bugging/react-use-downloader#17]
**Describe the bug**
When building with esbuild, I get the following error: `ReferenceError: process is not defined.`

**To Reproduce**
1. create a sample app with esbuild
2. add your component 

**Additional context**
https://github.com/the-bugging/react-use-downloader/blob/e473b8c31e6fc680da1d89b5236cabeec657a99d/src/index.ts#L124

update to 
```JS
 const debugMode = process?.env?.REACT_APP_DEBUG_MODE
```

**Comment by MarcosRS** [comment]
still errors when it tries to access process. This worked for me : 
```
  let debugMode = false;
  try {
    if (process) {
      debugMode = !!process?.env?.REACT_APP_DEBUG_MODE;
    }
  } catch (err) {
    //Your error handling
  }
```

**Comment by olavoparno** [comment]
Hey guys, thank you for opening this issue. I'm having a hard time managing time in between things, you know, would you be so kind opening a PR for this fix? I'd gladly review and I'd really appreciate it

**Comment by olavoparno** [comment]
@all-contributors please add @peranosborn and @MarcosRS for bug, idea

**Comment by olavoparno** [comment]
Thank you again, guys, it should be fixed now on version react-use-downloader@1.2.5. If anything just let me know.

**Comment by olavoparno** [comment]
@all-contributors please add @MarcosRS for bug, idea

**Comment by peranosborn** [comment]
Thank you for fixing this issue for us
