### ISSUE TITLE
ReferenceError: process is not defined (Part II)

### ISSUE THREAD

**Issue by 9swampy** [the-bugging/react-use-downloader#20]
I'm still getting the process is not defined error using 1.2.5.

Implementing akin to how MarcoRS had proposed fixes for me

              still errors when it tries to access process. This worked for me : 
```
  let debugMode = false;
  try {
    if (process) {
      debugMode = !!process?.env?.REACT_APP_DEBUG_MODE;
    }
  } catch (err) {
    //Your error handling
  }
```

_Originally posted by @MarcosRS in https://github.com/the-bugging/react-use-downloader/issues/17#issuecomment-1936659505_

**Comment by 9swampy** [comment]
Pull request: https://github.com/the-bugging/react-use-downloader/pull/21#issue-2228728038

**Comment by olavoparno** [comment]
Thank you man for looking into it and opening the PR! Really appreciate it. @all-contributors please add @9swampy for bug

**Comment by olavoparno** [comment]
Version 1.2.6 is live
