### ISSUE TITLE
...options not honoured

### ISSUE THREAD

**Issue by 9swampy** [the-bugging/react-use-downloader#23]
**Describe the bug**
If Fetch RequestInit ...options supplied then the default method: GET overrides supplied.

**To Reproduce**
Attempt to provide a body; download will error because you can't GET with a body.
`useDownloader(
        {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(''),
        }`

**Comment by olavoparno** [comment]
Thank you once again for raising this issue.

**Comment by olavoparno** [comment]
@9swampy once again, thank you man! Check version 1.2.7 please
