### ISSUE TITLE
Allow options to be updated

### ISSUE THREAD

**Issue by davecarlson** [the-bugging/react-use-downloader#25]
**Is your feature request related to a problem? Please describe.**

Currently, you can only to pass options.headers on first render.
This makes it impossible to 'update' things such as the token, if required.

**Describe the solution you'd like**
setOptions() to update the stored options:
eg: 
```
setOptions({
...options,
headers: {
  Authorization: 'Bearer anUpdatedToken`
}
```

**Describe alternatives you've considered**
Right now, I have to wrap my component in another component that async gets the bearer token.
<img width="1048" alt="Screenshot 2024-04-16 at 15 39 39" src="https://github.com/the-bugging/react-use-downloader/assets/299702/4cdcbea8-5064-4231-8037-8870e5002749">

**Additional context**

**Comment by olavoparno** [comment]
@davecarlson thank you for opening this issue. Will look into it as soon as possible.

**Comment by davecarlson** [comment]
Thanks ! In our use case, the tokens are only valid 30 seconds, and thus need to be fetched onClick ideally ( a new token each time )

**Comment by 9swampy** [comment]
@davecarlson would the proposed PR work for you?

**Comment by olavoparno** [comment]
@all-contributors please add @davecarlson for ideas!

**Comment by olavoparno** [comment]
Hey you all, please check version 1.2.8 :) once again, thank you all for the amazing contributions!
