### ISSUE TITLE
Allow custom timeout

### ISSUE THREAD

**Issue by esemeniuc** [the-bugging/react-use-downloader#6]
When downloading from a slow backend, the request will time out. Eg. backend takes 10 seconds to generate a file, then react-use-downloader will stop at ~3 seconds

Having an optional flag, such as `download(fileUrl, filename, timeout)` would be great. For example, timeout could default to 3 seconds, but can be manually overridden

**Comment by olavoparno** [comment]
@esemeniuc hey! thanks for opening this issue. Yeah, it makes total sense to me. I will look into it as soon as possible, ok?

Again, thanks for the tip ;)

**Comment by esemeniuc** [comment]
I just realized I didn't have CORS set to allow all hosts, it looks like that was causing me the error, so everything works now :) The suggestion still could be useful, but it can be left as a suggestion for now!

**Comment by olavoparno** [comment]
@all-contributors please add @esemeniuc for ideas!

**Comment by olavoparno** [comment]
@esemeniuc could you try version 1.1.7? It's got timeout now as you suggested.

Thank you again :)

**Comment by esemeniuc** [comment]
Awesome, I will test on Monday :)

**Comment by esemeniuc** [comment]
It works, thank you! One suggestion would be to specify the unit for timeout in a comment, or in the variable name (eg `timeoutMs`)
