### ISSUE TITLE
Invalid hook call issue

### ISSUE THREAD

**Issue by davdi1337** [the-bugging/react-use-downloader#9]
**Describe the bug**
Im always get Invalid Hook Call error in version 1.1.7
Tried to use in CodeSandbox and with older versions working with no problems, but in 1.1.7 doesn't really wants to work.
Copied exactly the same code from [this](https://github.com/olavoparno/react-use-downloader#usage) GitHub page, and still get invalid hook call error, so i don't really know what should i do with this

**Additional context**
A quick screenshot about my problem
![image](https://user-images.githubusercontent.com/66253422/193128526-598538a2-e000-4053-822c-edc0f8d09604.png)

**Comment by TarikDervisevicVisiot** [comment]
I am getting the same error, tried older versions and they work fine

**Comment by olavoparno** [comment]
Hello guys, I am sorry for the delayed answer. Been stuck with lots of things right now. Let's try with a newer version. I think I might know what has happened.

Thanks for the issue and troubleshooting so far.

**Comment by olavoparno** [comment]
Could you @davdi1337 abd @TarikDervisevicVisiot please try again with version 1.2.0?

**Comment by davdi1337** [comment]
> Could you @davdi1337 abd @TarikDervisevicVisiot please try again with version 1.2.0?

Seems working now

**Comment by olavoparno** [comment]
Thanks for the feedback and sorry for the inconvenience and happy coding!

@all-contributors please add @davdi1337 and @TarikDervisevicVisiot for bug
